Refacto/backend entities
WildCodeSchool/2023-11-wns-bleu-g4 pull request #112
Opened 2024-06-07 22:18 UTC by xakaz

#91 
#92

2024-06-09 08:12 UTC, HpJkR approved these changes

2024-06-09 08:50 UTC, Arkantik requested changes

2024-06-09 08:50 UTC, Arkantik commented on backend/src/entities/BookingItem.ts
Les propriétés de l'entité sont différentes du MPD/MLD

2024-06-09 08:50 UTC, Arkantik commented on backend/src/entities/ParentCategory.ts
>  	thumbnail: string
Le field thumbnail appartient à "category", cf image de la home page 
![category](https://github.com/WildCodeSchool/2023-11-wns-bleu-g4/assets/95821033/7707521e-50a2-47b2-9e4d-4e062d09933a)

2024-06-09 08:50 UTC, Arkantik commented on backend/src/entities/Review.ts
>  	@Field(() => Product, { nullable: true })
Je ne suis pas sur que le nullable: true soit correcte, une review sera forcement liée à un user ET un product, sinon elle n'existe pas.

2024-06-10 07:01 UTC, chambrin approved these changes

2024-06-10 15:35 UTC, Arkantik approved these changes

2024-06-11 05:52 UTC, merged