Create Agency Entity
WildCodeSchool/2023-11-wns-bleu-g4 pull request #60
Opened 2024-05-03 21:13 UTC by xakaz

#14

2024-05-04 08:48 UTC, chambrin approved these changes

2024-05-07 15:26 UTC, Arkantik commented on backend/src/entities/Agency.ts
> +	zipcode: number
Je mettrais le zipcode en string car dans certains pays il peut contenir des lettres en plus des chiffres

2024-05-07 15:32 UTC, Arkantik requested changes
J'ai ajouté quelques notes sur certains point qui je pense doivent être modifiés, on peut en discuter si besoin

2024-05-07 15:32 UTC, Arkantik commented on backend/src/resolvers/AgencyResolver.ts
Le code commenté lié à la gestion des droits devrait être gardé car nous voulons uniquement les mutations d'agences pour un admin.

2024-05-07 15:32 UTC, Arkantik commented on backend/src/resetDb.ts
> +		zipcode: 31330,
Il faudra penser à changer  le zipcode en string sinon le script lancera une erreur

2024-05-07 15:32 UTC, Arkantik commented on backend/src/entities/Agency.ts
> +	zipcode: number
Je mettrais le zipcode en string car dans certains pays il peut contenir des lettres en plus des chiffres

2024-05-07 15:36 UTC, Arkantik commented on backend/src/entities/Agency.ts
> +	zipcode: number
Dans l'entité User nous avions mis postcode, est-ce qu'on garde postcode or zipcode pour la référence au code postal afin qu'on nomme de la même façon dans les entités ?

2024-06-03 14:35 UTC, Arkantik approved these changes

2024-06-03 14:36 UTC, merged